"""
Report generator for weekly academic paper summaries.

Generates beautifully formatted Markdown reports grouped by journal category,
with HTML card layouts, summary tables, and optional AI-powered summarization.
"""

import logging
import re
from datetime import datetime
from pathlib import Path

from config.settings import REPORTS_DIR, LLM_API_KEY, LLM_BASE_URL, LLM_MODEL

logger = logging.getLogger(__name__)

# ── Category display configuration ────────────────────────────────────

CATEGORY_EMOJI = {
    "Entrepreneurship": "\U0001f680",
    "Innovation & Technology Policy": "\U0001f4a1",
    "Management": "\U0001f4d0",
    "Strategy": "\u265f\ufe0f",
    "Organization": "\U0001f3db\ufe0f",
    "Management Science": "\U0001f4ca",
    "International Business": "\U0001f30d",
    "Practitioner": "\U0001f527",
    "Marketing": "\U0001f4e3",
    "Information Systems": "\U0001f4bb",
    "Operations Management": "\u2699\ufe0f",
    "Operations Research": "\U0001f52c",
    "OB & HR": "\U0001f465",
    "Accounting": "\U0001f4d2",
    "Finance": "\U0001f4b0",
    "Economics": "\U0001f4c8",
    "Ethics": "\u2696\ufe0f",
}


def generate_report(
    papers: list[dict],
    title: str | None = None,
    output_dir: Path | None = None,
) -> Path:
    """Generate a beautifully formatted Markdown report from fetched papers.

    Args:
        papers: List of normalized paper dicts from fetcher.
        title: Report title. Defaults to "Weekly Academic Paper Summary".
        output_dir: Output directory. Defaults to REPORTS_DIR.

    Returns:
        Path to the generated report file.
    """
    if output_dir is None:
        output_dir = REPORTS_DIR
    output_dir.mkdir(parents=True, exist_ok=True)

    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    if title is None:
        title = "Weekly Academic Paper Summary"

    filename = f"report_{now.strftime('%Y%m%d_%H%M%S')}.md"
    filepath = output_dir / filename

    # Group papers by category
    grouped = _group_by_category(papers)

    # Compute stats
    ft50_count = sum(1 for p in papers if p.get("in_ft50"))
    utd24_count = sum(1 for p in papers if p.get("in_utd24"))
    high_rel = sum(1 for p in papers if p.get("innovation_relevance") == "high")

    lines: list[str] = []

    # ── Header ──────────────────────────────────────────────────────
    lines.append('<div align="center">\n')
    lines.append(f"# \U0001f4da {title}\n")
    lines.append(
        f"**{date_str}** \u00b7 Generated by "
        "[AI Academia Bot](https://github.com/coujasmine/AI-academia-bot)\n"
    )
    lines.append("</div>\n")
    lines.append("---\n")

    # ── Statistics cards ────────────────────────────────────────────
    lines.append("<table>")
    lines.append("<tr>")
    lines.append(
        f'<td align="center"><strong>\U0001f4c4 Total</strong><br/>'
        f"<code>{len(papers)}</code> papers</td>"
    )
    lines.append(
        f'<td align="center"><strong>\U0001f3db\ufe0f FT50</strong><br/>'
        f"<code>{ft50_count}</code> papers</td>"
    )
    lines.append(
        f'<td align="center"><strong>\U0001f4ca UTD24</strong><br/>'
        f"<code>{utd24_count}</code> papers</td>"
    )
    lines.append(
        f'<td align="center"><strong>\U0001f3af Innovation</strong><br/>'
        f"<code>{high_rel}</code> papers</td>"
    )
    lines.append("</tr>")
    lines.append("</table>\n")
    lines.append("---\n")

    # ── Summary table (汇总表格) ───────────────────────────────────
    lines.append('<div align="center">\n')
    lines.append("## \U0001f5c2\ufe0f Paper Overview\n")
    lines.append("</div>\n")
    lines.append(_build_summary_table(grouped))
    lines.append("")
    lines.append("---\n")

    # ── Paper sections by category ──────────────────────────────────
    global_index = 0
    for cat, cat_papers in grouped.items():
        emoji = CATEGORY_EMOJI.get(cat, "\U0001f4c4")
        lines.append(f"## {emoji} {cat}\n")
        for paper in cat_papers:
            global_index += 1
            lines.append(_format_paper(paper, global_index))
        lines.append("---\n")

    # ── Footer ──────────────────────────────────────────────────────
    lines.append('<div align="center">')
    lines.append(
        '<sub>Generated by <a href="https://github.com/coujasmine/AI-academia-bot">'
        "AI Academia Bot</a> \u00b7 "
        'Data from <a href="https://openalex.org">OpenAlex</a></sub>'
    )
    lines.append("</div>")

    content = "\n".join(lines)
    filepath.write_text(content, encoding="utf-8")
    logger.info("Report generated: %s", filepath)
    return filepath


def _build_summary_table(grouped: dict[str, list[dict]]) -> str:
    """Build an HTML summary table listing all papers at a glance."""
    rows: list[str] = []
    rows.append("| # | Title | Journal | Date | Tags |")
    rows.append("|--:|-------|---------|------|------|")

    idx = 0
    for cat, cat_papers in grouped.items():
        emoji = CATEGORY_EMOJI.get(cat, "\U0001f4c4")
        # Category separator row
        rows.append(
            f"| | **{emoji} {cat}** | | | |"
        )
        for paper in cat_papers:
            idx += 1
            title = paper.get("title", "Untitled")
            # Truncate long titles for the table
            display_title = title if len(title) <= 70 else title[:67] + "..."
            doi = paper.get("doi", "")
            url = doi if doi else paper.get("url", "")
            if url:
                display_title = f"[{display_title}]({url})"

            journal = paper.get("journal_abbr", "")
            pub_date = paper.get("publication_date", "")

            tags = []
            if paper.get("in_ft50"):
                tags.append("`FT50`")
            if paper.get("in_utd24"):
                tags.append("`UTD24`")
            rel = paper.get("innovation_relevance", "")
            if rel == "high":
                tags.append("`Innovation-Core`")
            elif rel == "medium":
                tags.append("`Innovation-Related`")
            tag_str = " ".join(tags)

            rows.append(
                f"| {idx} | {display_title} | {journal} | {pub_date} | {tag_str} |"
            )

    return "\n".join(rows)


def _group_by_category(papers: list[dict]) -> dict[str, list[dict]]:
    """Group papers by journal category, with innovation-related categories first."""
    category_order = [
        "Entrepreneurship",
        "Innovation & Technology Policy",
        "Management",
        "Strategy",
        "Organization",
        "Management Science",
        "International Business",
        "Practitioner",
        "Marketing",
        "Information Systems",
        "Operations Management",
        "Operations Research",
        "OB & HR",
        "Accounting",
        "Finance",
        "Economics",
        "Ethics",
    ]
    grouped: dict[str, list[dict]] = {}
    for paper in papers:
        cat = _get_category(paper)
        grouped.setdefault(cat, []).append(paper)

    # Sort by predefined order
    ordered = {}
    for cat in category_order:
        if cat in grouped:
            ordered[cat] = grouped.pop(cat)
    # Add any remaining categories
    for cat in sorted(grouped.keys()):
        ordered[cat] = grouped[cat]
    return ordered


def _get_category(paper: dict) -> str:
    """Get the category for a paper based on its journal."""
    from config.journals import JOURNALS

    abbr = paper.get("journal_abbr", "")
    for j in JOURNALS:
        if j["abbr"] == abbr:
            return j["category"]
    return "Other"


def _format_paper(paper: dict, index: int) -> str:
    """Format a single paper as a card-styled Markdown/HTML section."""
    title = paper.get("title", "Untitled")
    doi = paper.get("doi", "")
    url = doi if doi else paper.get("url", "")

    # Build metadata table rows
    meta_rows: list[str] = []

    journal = paper.get("journal_name", "")
    abbr = paper.get("journal_abbr", "")
    if journal:
        meta_rows.append(f"| **\U0001f4f0 Journal** | {journal} ({abbr}) |")

    authors = paper.get("authors", [])
    if authors:
        author_str = " \u00b7 ".join(authors[:5])
        if len(authors) > 5:
            author_str += f" ... (+{len(authors) - 5} more)"
        meta_rows.append(f"| **\U0001f464 Authors** | {author_str} |")

    pub_date = paper.get("publication_date", "")
    if pub_date:
        meta_rows.append(f"| **\U0001f4c5 Published** | {pub_date} |")

    # Tags
    tags = []
    if paper.get("in_ft50"):
        tags.append("`FT50`")
    if paper.get("in_utd24"):
        tags.append("`UTD24`")
    rel = paper.get("innovation_relevance", "")
    if rel == "high":
        tags.append("`Innovation-Core`")
    elif rel == "medium":
        tags.append("`Innovation-Related`")
    if paper.get("open_access"):
        tags.append("`Open Access`")
    if tags:
        meta_rows.append(f"| **\U0001f3f7\ufe0f Tags** | {' '.join(tags)} |")

    # DOI link
    if url:
        display_url = url.replace("https://doi.org/", "")
        meta_rows.append(f"| **\U0001f517 DOI** | [{display_url}]({url}) |")

    # Build the metadata table
    meta_table = "| | |\n|---|---|\n" + "\n".join(meta_rows)

    # Abstract
    abstract = paper.get("abstract", "")
    if abstract:
        abstract = re.sub(r"<[^>]+>", "", abstract).strip()
        if len(abstract) > 800:
            abstract = abstract[:800] + "..."
        abstract_section = f"**Abstract** \u2014 {abstract}"
    else:
        abstract_section = "**Abstract** \u2014 *Abstract not available*"

    # Topics as tags
    topics = paper.get("topics", [])
    if topics:
        topic_tags = " ".join(f"`{t}`" for t in topics)
        topics_section = f"\n**Topics:** {topic_tags}\n"
    else:
        topics_section = ""

    # Assemble as card
    card = f"""<table><tr><td>

### {index} \u00b7 {title}

{meta_table}

{abstract_section}
{topics_section}
</td></tr></table>
"""
    return card


# ── AI-Powered Summary (Optional) ────────────────────────────────────


def generate_ai_summary(papers: list[dict]) -> str:
    """Use an LLM to generate a high-level summary of this week's papers.

    Requires LLM_API_KEY to be configured. Returns empty string if not available.
    """
    if not LLM_API_KEY:
        logger.info("LLM_API_KEY not set, skipping AI summary")
        return ""

    try:
        import openai

        client = openai.OpenAI(api_key=LLM_API_KEY, base_url=LLM_BASE_URL)
    except ImportError:
        logger.warning("openai package not installed, skipping AI summary")
        return ""

    # Prepare paper summaries for the prompt
    paper_texts = []
    for p in papers[:30]:  # Limit to 30 papers to fit context
        text = f"- [{p.get('journal_abbr', '')}] {p.get('title', '')}"
        abstract = p.get("abstract", "")
        if abstract:
            text += f": {abstract[:200]}"
        paper_texts.append(text)

    prompt = f"""You are an academic research analyst specializing in management,
innovation, and entrepreneurship. Below is a list of recently published papers
from top management journals (FT50/UTD24).

Please provide:
1. A brief executive summary (2-3 paragraphs) of the key themes and trends
2. Highlight 3-5 papers most relevant to innovation and entrepreneurship research
3. Note any emerging research directions

Papers:
{chr(10).join(paper_texts)}

Please write in both English and Chinese (中英双语)."""

    try:
        response = client.chat.completions.create(
            model=LLM_MODEL,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=2000,
            temperature=0.3,
        )
        return response.choices[0].message.content
    except Exception as e:
        logger.error("AI summary generation failed: %s", e)
        return ""


def format_ai_summary_section(ai_summary: str) -> str:
    """Format the AI summary as a styled Markdown section for appending to reports."""
    lines = [
        "",
        "---\n",
        '<div align="center">\n',
        "### \U0001f916 AI Trend Summary\n",
        "</div>\n",
        f"> {ai_summary}\n",
        "---\n",
    ]
    return "\n".join(lines)
